// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class Bird
    {
        public Bird()
        {
            BirdEventBird1Navigation = new HashSet<BirdEvent>();
            BirdEventBird2Navigation = new HashSet<BirdEvent>();
            JoinEvent = new HashSet<JoinEvent>();
        }

        [Key]
        [StringLength(10)]
        public string BirdId { get; set; }
        [Required]
        public string BirdName { get; set; }
        [Required]
        [StringLength(10)]
        public string MemberId { get; set; }
        [Required]
        [StringLength(10)]
        public string BirdTypeId { get; set; }
        [Required]
        public string Image { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Size { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Weight { get; set; }
        public int Age { get; set; }
        public bool Status { get; set; }

        [ForeignKey("BirdTypeId")]
        [InverseProperty("Bird")]
        public virtual BirdType BirdType { get; set; }
        [ForeignKey("MemberId")]
        [InverseProperty("Bird")]
        public virtual Member Member { get; set; }
        [InverseProperty("Bird1Navigation")]
        public virtual ICollection<BirdEvent> BirdEventBird1Navigation { get; set; }
        [InverseProperty("Bird2Navigation")]
        public virtual ICollection<BirdEvent> BirdEventBird2Navigation { get; set; }
        [InverseProperty("Bird")]
        public virtual ICollection<JoinEvent> JoinEvent { get; set; }
    }
}