// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class BirdEvent
    {
        [Key]
        [Column("BirdEventID")]
        [StringLength(10)]
        public string BirdEventId { get; set; }
        [Required]
        [StringLength(10)]
        public string Bird1 { get; set; }
        [Required]
        [StringLength(10)]
        public string Bird2 { get; set; }
        public int? Bird1Score { get; set; }
        public int? Bird2Score { get; set; }
        [StringLength(10)]
        public string Winner { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EventDate { get; set; }
        [Required]
        [StringLength(10)]
        public string PostId { get; set; }

        [ForeignKey("Bird1")]
        [InverseProperty("BirdEventBird1Navigation")]
        public virtual Bird Bird1Navigation { get; set; }
        [ForeignKey("Bird2")]
        [InverseProperty("BirdEventBird2Navigation")]
        public virtual Bird Bird2Navigation { get; set; }
        [ForeignKey("PostId")]
        [InverseProperty("BirdEvent")]
        public virtual Post Post { get; set; }
    }
}