// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class BirdType
    {
        public BirdType()
        {
            Bird = new HashSet<Bird>();
            BirdTypeEvent = new HashSet<BirdTypeEvent>();
        }

        [Key]
        [StringLength(10)]
        public string BirdTypeId { get; set; }
        [Required]
        public string BirdTypeName { get; set; }
        public string BirdTypeDescription { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [InverseProperty("BirdType")]
        public virtual ICollection<Bird> Bird { get; set; }
        [InverseProperty("BirdType")]
        public virtual ICollection<BirdTypeEvent> BirdTypeEvent { get; set; }
    }
}