// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class BirdTypeEvent
    {
        [Key]
        [StringLength(10)]
        public string BirdTypeId { get; set; }
        [Key]
        [StringLength(10)]
        public string PostId { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateTime { get; set; }

        [ForeignKey("BirdTypeId")]
        [InverseProperty("BirdTypeEvent")]
        public virtual BirdType BirdType { get; set; }
        [ForeignKey("PostId")]
        [InverseProperty("BirdTypeEvent")]
        public virtual Post Post { get; set; }
    }
}