// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class Category
    {
        public Category()
        {
            PostCategory = new HashSet<PostCategory>();
        }

        [Key]
        [Column("CategoryID")]
        [StringLength(10)]
        public string CategoryId { get; set; }
        [Required]
        public string CategoryName { get; set; }
        public string Description { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<PostCategory> PostCategory { get; set; }
    }
}