// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class Comment
    {
        public Comment()
        {
            InverseReply = new HashSet<Comment>();
        }

        [Required]
        [Column("MemberID")]
        [StringLength(10)]
        public string MemberId { get; set; }
        [Required]
        [Column("PostID")]
        [StringLength(10)]
        public string PostId { get; set; }
        [Column("ReplyID")]
        [StringLength(10)]
        public string ReplyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTime { get; set; }
        [Required]
        public string CommentContent { get; set; }
        public bool Status { get; set; }
        [Key]
        [Column("CommentID")]
        [StringLength(10)]
        public string CommentId { get; set; }

        [ForeignKey("MemberId")]
        [InverseProperty("Comment")]
        public virtual Member Member { get; set; }
        [ForeignKey("PostId")]
        [InverseProperty("Comment")]
        public virtual Post Post { get; set; }
        [ForeignKey("ReplyId")]
        [InverseProperty("InverseReply")]
        public virtual Comment Reply { get; set; }
        [InverseProperty("Reply")]
        public virtual ICollection<Comment> InverseReply { get; set; }
    }
}