// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    [Index("ManagerUserName", Name = "IX_Manager", IsUnique = true)]
    [Index("ManagerEmail", Name = "IX_Manager_1", IsUnique = true)]
    [Index("ManagerPhone", Name = "IX_Manager_2", IsUnique = true)]
    public partial class Manager
    {
        public Manager()
        {
            Blog = new HashSet<Blog>();
            Post = new HashSet<Post>();
            Report = new HashSet<Report>();
        }

        [Key]
        [Column("ManagerID")]
        [StringLength(10)]
        public string ManagerId { get; set; }
        [Required]
        [StringLength(50)]
        public string ManagerUserName { get; set; }
        [Required]
        [StringLength(15)]
        public string ManagerPhone { get; set; }
        [Required]
        [StringLength(50)]
        public string ManagerPassword { get; set; }
        [Required]
        [StringLength(100)]
        public string ManagerEmail { get; set; }
        public bool ManagerStatus { get; set; }
        [Required]
        public string ManagerFullName { get; set; }
        [Required]
        public string ManagerImage { get; set; }

        [InverseProperty("Manager")]
        public virtual ICollection<Blog> Blog { get; set; }
        [InverseProperty("Manager")]
        public virtual ICollection<Post> Post { get; set; }
        [InverseProperty("Manager")]
        public virtual ICollection<Report> Report { get; set; }
    }
}