// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class Notification
    {
        [Key]
        [Column("NotificationID")]
        [StringLength(10)]
        public string NotificationId { get; set; }
        [Required]
        public string NotificationContent { get; set; }
        public bool NotificationStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime NotificationDateTime { get; set; }
        [Required]
        public string NotificationTitle { get; set; }
        [Required]
        [Column("MemberID")]
        [StringLength(10)]
        public string MemberId { get; set; }

        [ForeignKey("MemberId")]
        [InverseProperty("Notification")]
        public virtual Member Member { get; set; }
    }
}