// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class PostCategory
    {
        [Key]
        [Column("PostID")]
        [StringLength(10)]
        public string PostId { get; set; }
        [Key]
        [Column("CategoryID")]
        [StringLength(10)]
        public string CategoryId { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("PostCategory")]
        public virtual Category Category { get; set; }
        [ForeignKey("PostId")]
        [InverseProperty("PostCategory")]
        public virtual Post Post { get; set; }
    }
}