// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class Post
    {
        public Post()
        {
            BirdEvent = new HashSet<BirdEvent>();
            BirdTypeEvent = new HashSet<BirdTypeEvent>();
            Comment = new HashSet<Comment>();
            JoinEvent = new HashSet<JoinEvent>();
            Like = new HashSet<Like>();
            Media = new HashSet<Media>();
            PostCategory = new HashSet<PostCategory>();
            ProcessEvent = new HashSet<ProcessEvent>();
            Report = new HashSet<Report>();
        }

        [Key]
        [Column("PostID")]
        [StringLength(10)]
        public string PostId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PostCreateAt { get; set; }
        [Required]
        public string PostTitle { get; set; }
        [Required]
        public string PostDescription { get; set; }
        public bool PostIsEvent { get; set; }
        [Required]
        [StringLength(50)]
        public string PostStatus { get; set; }
        public int PostNumberLike { get; set; }
        public int PostNumberJoin { get; set; }
        public string EventLocation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventEndDate { get; set; }
        [Required]
        [Column("MemberID")]
        [StringLength(10)]
        public string MemberId { get; set; }
        [Column("ManagerID")]
        [StringLength(10)]
        public string ManagerId { get; set; }

        [ForeignKey("ManagerId")]
        [InverseProperty("Post")]
        public virtual Manager Manager { get; set; }
        [ForeignKey("MemberId")]
        [InverseProperty("Post")]
        public virtual Member Member { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<BirdEvent> BirdEvent { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<BirdTypeEvent> BirdTypeEvent { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Comment> Comment { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<JoinEvent> JoinEvent { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Like> Like { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Media> Media { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<PostCategory> PostCategory { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<ProcessEvent> ProcessEvent { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Report> Report { get; set; }
    }
}