// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class ProcessEvent
    {
        [Key]
        [Column("ProcessID")]
        [StringLength(10)]
        public string ProcessId { get; set; }
        [Required]
        [Column("PostID")]
        [StringLength(10)]
        public string PostId { get; set; }
        [Required]
        public string EventRule { get; set; }
        [Required]
        public string EventReward { get; set; }

        [ForeignKey("PostId")]
        [InverseProperty("ProcessEvent")]
        public virtual Post Post { get; set; }
    }
}