// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BCMS.Models
{
    public partial class ReportType
    {
        public ReportType()
        {
            Report = new HashSet<Report>();
        }

        [Key]
        [Column("ReportTypeID")]
        [StringLength(10)]
        public string ReportTypeId { get; set; }
        [Required]
        [StringLength(10)]
        public string ReportTypeName { get; set; }

        [InverseProperty("ReportTypeNavigation")]
        public virtual ICollection<Report> Report { get; set; }
    }
}